name: "Build"

on:
  pull_request:
  push:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      CUDA_MAJOR_VERSION: 12
      CUDA_MINOR_VERSION: 9
      TENSORRT_VERSION: 10.11.0.33-1+cuda12.9

    steps:
      - uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: setup
        run: |
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb
          sudo dpkg -i cuda-keyring_1.1-1_all.deb
          sudo apt update
          sudo apt install -y \
            libavutil-dev \
            libavdevice-dev \
            cuda-cudart-dev-$CUDA_MAJOR_VERSION-$CUDA_MINOR_VERSION \
            cuda-crt-$CUDA_MAJOR_VERSION-$CUDA_MINOR_VERSION \
            libnvinfer10=$TENSORRT_VERSION \
            libnvinfer-headers-dev=$TENSORRT_VERSION \
            libnvinfer-dev=$TENSORRT_VERSION \
            libnvinfer-plugin10=$TENSORRT_VERSION \
            libnvinfer-headers-plugin-dev=$TENSORRT_VERSION \
            libnvinfer-plugin-dev=$TENSORRT_VERSION
          wget https://github.com/CVCUDA/CV-CUDA/releases/download/v0.15.0-beta/cvcuda-lib-0.15.0-cuda12-x86_64-linux.deb
          sudo dpkg -i cvcuda-lib-0.15.0-cuda12-x86_64-linux.deb
          wget https://github.com/CVCUDA/CV-CUDA/releases/download/v0.15.0-beta/cvcuda-dev-0.15.0-cuda12-x86_64-linux.deb
          sudo dpkg -i cvcuda-dev-0.15.0-cuda12-x86_64-linux.deb

      - name: bazel-build-and-test
        run: |
          bazel build //... && bazel test //...
